# Generated by Django 4.0.6 on 2022-08-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
