# Generated by Django 4.0.6 on 2022-08-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseApprentice', to='api.courses'),
        ),
    ]
