# Generated by Django 4.0.6 on 2022-08-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_courses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeAssociente', to='api.typeassociente'),
        ),
    ]
